config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'process', to: 'pages#process'

  LINKS.each do |path, url|
    get path.to_s.gsub("_","/"), to: redirect(url)
  end

  REDIRECTS.each do |from, to|
    get from, to: redirect(to)
    get "#{from}/*video", to: redirect("#{to}/%{video}"), constraints: { video: /.*/ }
  end

  resources :channels, only: [:index, :new, :create]
  resources :videos, only: [:index, :new, :create]

  resources :channels, path: '/', except: [:index, :new, :create] do
    member do
      get :sync, :edit # fixes the video path taking over
    end
    resources :videos, path: '/', except: [:index, :new, :create] do
      member do
        get :sync
      end
    end
  end
end

app/models/video.rb
class Video < ApplicationRecord
  include Discard::Model
  extend FriendlyId

  before_save :set_slug

  belongs_to :channel

  has_many :sources, class_name: "VideoSource", dependent: :destroy
  has_one :peertube, class_name: "VideoSource::Peertube"
  has_one :youtube, class_name: "VideoSource::Youtube"

  scope :published, -> { where.not(published_at: nil) }
  scope :latest, -> { order(published_at: :desc) }
  scope :random, -> { order("RANDOM()") }
  scope :this_week, -> { where(published_at: 1.week.ago..1.second.ago) }

  validates :slug, uniqueness: { scope: :channel_id }

  friendly_id :name, use: :scoped, scope: :channel

  accepts_nested_attributes_for :youtube

  def to_s
    name
  end

  def image
    youtube&.image || VIDEO_PLACEHOLDER_IMAGE
  end

  def sync!
    youtube.sync!

    self.touch
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :sync, :update, :destroy]
  before_action :set_video, only: [:show, :edit, :sync, :update, :destroy]
  before_action :not_production, only: [:new, :create, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @q = Video.kept.includes(:channel, :sources).published.latest.ransack(params[:q])
    @videos = @q.result(distinct: true)
    @pagy, @videos = pagy(@videos, items: params[:items])
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @videos = @channel.videos.includes(:channel, :sources).random.limit(5)
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # GET /channels/1/sync
  def sync
    @video.sync!

    redirect_to channel_video_path(@channel, @video)
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to channel_video_path(@video.channel, @video), notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to channel_video_path(@video.channel, @video), notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.friendly.find(params[:channel_id])
    end

    def set_video
      if @video = @channel.videos.find_by(slug: params[:id])
        return @video
      elsif @source = VideoSource.where('lower(ident) = ?', params[:id].downcase).first
        redirect_to channel_video_path(@channel, @source.video)
      else
        raise ActiveRecord::RecordNotFound
      end
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:name, :slug, :description, :published_at, :channel_id)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: [video.channel, video], local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="field">
    <%= form.label :channel %>
    <%= form.text_field :channel %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<% simple = defined?(locals[:simple]) %>

<div class="col mb-4">
  <div class="card card-block">
    <%= link_to(image_tag(video.image, class: "card-img-top", alt: video.name), [video.channel, video]) %>
    <div class="card-body p-2">
      <div  style="height: 100px">
        <%= logo_tag video.channel %>
        <h5 class="card-title mb-2 overflow-hidden" style="height: 72px">
          <small class="font-weight-bold">
            <%= link_to video.name.html_safe, [video.channel, video], title: video.name.html_safe %>
          </small>
        </h5>
        <div class="mb-0 d-block overflow-hidden text-nowrap">
          <small class="d-inline-block text-truncate font-weight-bold" style="max-width: 70%;">
            <%= link_to video.channel.name, video.channel, title: video.channel.name %>
          </small>
          <small class="d-inline-block text-truncate" style="max-width: 30%;">
            &middot;
            <%= time_ago_in_words(video.published_at).gsub("about", "") %> ago
          </small>
        </div>
      </div>
      <% if !simple %>
        <div class="btn-group btn-group-sm btn-block mt-2">
          <% video.sources.each do |source| %>
            <%= link_to I18n.t(source.kind), source.url, class: "btn btn-#{ source.kind }", target: :blank %>
          <% end %>
        </div>
      <% end %>
    </div>
    <% if !simple && Rails.env.development? %>
      <div class="card-footer p-2">
        <div class="btn-group btn-group-sm btn-block">
          <%= link_to "Edit", edit_channel_video_path(video.channel, video), class: "btn btn-light btn-outline-dark" %>
          <%= link_to 'Destroy', [video.channel, video], method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
        </div> 
      </div>
    <% end %>
  </div>
</div>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', [@channel, @video] %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<div class="container-fluid">
  <div class="row my-2">
    <div class="col">
      <div class="d-block d-md-flex justify-content-between">
        <h1 class="h2 mb-2 mr-auto">
          <%= link_to I18n.t(:videos), videos_path %>
        </h1>

        <div class="mb-2 mr-0 mr-md-2">
          <%= search_form_for @q, wrapper: :inline_form do |f| %>
            <div class="input-group">
              <%= f.input_field :name_or_slug_or_description_or_channel_name_or_channel_slug_cont, label: 'Search', class: 'form-control border-white border-top-none', type: :search %>
              <div class="input-group-append">
                <%= f.button :submit, class: 'btn-primary' %>
              </div>
            </div>
          <% end %>
        </div>

        <div class="mb-2">
          <%== pagy_bootstrap_combo_nav_js(@pagy) %>
        </div>
      </div>
    </div>

    <div class="col-12">
      <%= card_row do %>
        <% @videos.each do |video| %>
          <%= render video %>
        <% end %>
      <% end %>
    </div>
  </div>

  <%#= link_to 'New video', new_video_path %>
</div>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<%= content_for :head do %>
  <meta property="og:image" content="<%= @video.image %>">
  <meta name="description" content="<%= @video.description %>">
<% end %>

<div class="container-fluid">
  <div class="row mt-2">
    <div class="col col-sm-8 col-md-9">
      <div class="tab-content" id="pills-tabContent">
        <% @video.sources.order_by_type.each_with_index do |source, index| %>
          <% id = "video_sources-#{ source.kind }" %>
          <div class="tab-pane fade show <%= 'active' if (index == 0) %>" id="<%= id %>" role="tabpanel" aria-labelledby="<%= id %>">
            <div class="embed-responsive embed-responsive-16by9" style="max-height: 100vh">
              <iframe class="embed-responsive-item" src="<%= source.embed_url %>" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          </div>
        <% end %>
      </div>

      <ul class="nav nav-pills my-3" id="sources-tab" role="tablist">
        <% @video.sources.order_by_type.each_with_index do |source, index| %>
          <% id = "video_sources-#{ source.kind }" %>
          <li class="nav-item">
            <a class="nav-link <%= 'active' if (index == 0) %> source-<%= source.kind %>" id="<%= id %>" data-toggle="pill" href="#<%= id %>" role="tab" aria-controls="<%= id %>" aria-selected="true">
              <%= I18n.t source.kind %>
            </a>
          </li>
        <% end %>
      </ul>

      <div class="row overflow-hidden">
        <div class="col-12 col-md-9 col-lg-9 col-xl-10">
          <h1 class="h4 mb-0">
            <%= @video.name.html_safe %>
          </h1>
          
          <p class="my-0">
            <small>
              <%= @video.published_at %>
            </small>
          </p>

          <% if @video.description.present? %>
            <div class="links-target-blank">
              <%= simple_format markdown.render(@video.description).html_safe %>
            </div>
          <% end %>

          <p>
            <ul>
              <% @video.tags.each do |tag| %>
                <li><%= tag %></li>
              <% end %>
            </ul>
          </p>
        </div>

        <div class="col-12 col-md-3 col-lg-3 col-xl-2">
          <div class="overflow-hidden mb-1">
            <%= logo_tag @channel %>
            <div class="float-left" style="width: calc(100% - 50px)">
              <h5 class="mb-0">
                <small class="font-weight-bold">
                  <%= link_to @channel.name, @channel %>
                </small>
              </h5>
            </div>
          </div>
          <% if @channel.description.present? %>
            <small>
              <%= simple_format markdown.render(@channel.description).html_safe %>
            </small>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-12 col-sm-4 col-md-3">
      <div class="row row-cols-1">
        <%= render @videos, locals: { simple: true } %>
      </div>
    </div>
  </div>

  <% if Rails.env.development? %>
    <%= link_to 'Edit', edit_channel_video_path(@video.channel, @video) %>
    <%= link_to 'Sync', sync_channel_video_path(@channel, @video) %>
    <div>
      <%= @video.inspect %>
    </div>
    <div>
      <%= @video.youtube.inspect %>
    </div>
  <% end %>
</div>